language: python

python:
  - 3.7

env:
  - DJANGO=2.2.2

before_install:
  - export DJANGO_SETTINGS_MODULE=IamGO.settings
  - export PYTHONPATH=$HOME/builds/aleshkashell/IamGO
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

script:
  - python manage.py test